services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    ports:
      - 13002:9000
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - ./data:/app/data/
    environment:
      # --- Authentik OIDC ---
      OIDC_AUTH_ENABLED: true
      OIDC_PROVIDER_NAME: authentik
      OIDC_SIGNUP_ENABLED: true
      OIDC_CONFIGURATION_URL: https://${AUTHENTIK_DOMAIN}/application/o/${MEALIE_SLUGS}/.well-known/openid-configuration
      OIDC_CLIENT_ID: ${MEALIE_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${MEALIE_CLIENT_SECRET}
      OIDC_USER_GROUP: ${MEALIE_USER_GROUP}
      OIDC_ADMIN_GROUP: ${MEALIE_ADMIN_GROUP}
      OIDC_AUTO_REDIRECT: true
      OIDC_REMEMBER_ME: true
      ALLOW_PASSWORD_LOGIN: false
      ALLOW_SIGNUP: false
      PUID: 1000
      PGID: 1000
      TZ: Asiz/Seoul
      BASE_URL: https://mealie.junbeom.work
    networks:
      - npm_default
volumes:
  mealie-data: null
networks:
  npm_default:
    external: true
