---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Infrastructure & Network:
    - NPM+:
        href: http://192.168.50.200:10001
        description: "Reverse Proxy 및 SSL 관리"
        icon: nginx-proxy-manager.svg
    - Dockge:
        href: http://192.168.50.200:10000
        description: "도커 컨테이너 관리"
        icon: dockge.svg

- Security & Identity:
    - Authentik:
        href: http://192.168.50.200:11000/if/admin/
        description: "2단계 인증 및 SSO"
        icon: authentik.svg
    - VaultWarden:
        href: http://192.168.50.200:11002/admin/
        description: "비밀번호 관리자"
        icon: vaultwarden-light.svg

- Monitoring & Ops:
    - Uptime Kuma:
        href: http://192.168.50.200:12000
        description: "서비스 상태 모니터링"
        icon: uptime-kuma.svg
    - Dozzle:
        href: http://192.168.50.200:12001
        description: "로그 모니터링"
        icon: dozzle.svg
    - Scrutiny:
        href: http://192.168.50.200:12002
        description: "디스크 상태 모니터링"
        icon: scrutiny-light.svg
    - Tugtainer:
        href: http://192.168.50.200:12004
        description: "컨테이너 업데이트 관리 도구"
        icon: tugtainer.png

- Data & Storage:
    - FileBrowser:
        href: http://192.168.50.200:13001
        description: "나만의 드라이브"
        icon: filebrowser.svg
    - Syncthing:
        href: http://192.168.50.200:13002
        description: "프로젝트 실시간 동기화"
        icon: syncthing.svg
    - Pingvin-Share-X:
        href: http://192.168.50.200:13005
        description: "파일 공유 도구"
        icon: pingvin-share.svg
    - Paperless-NGX:
        href: http://192.168.50.200:13007
        description: "문서 관리"
        icon: paperless-ngx.svg

- Productivity & Development:
    - CloudBeaver:
        href: http://192.168.50.200:14000
        description: "데이터베이스 관리"
        icon: cloudbeaver.svg
    - IT-Tools:
        href: http://192.168.50.200:14001
        description: "개발 도구 모음"
        icon: it-tools-light.svg
    - Forgejo:
        href: http://192.168.50.200:14002
        description: "Git 저장소 관리"
        icon: forgejo.svg
    - Obsidian-Blog:
        href: http://192.168.50.200:14004
        description: "개인 지식 관리 및 블로그"
        icon: obsidian.svg
    - Outline:
        href: https://outline.junbeom.work
        description: "팀 위키 및 문서 관리"
        icon: outline.svg
    - AFFiNE:
        href: http://192.168.50.200:14006/admin
        description: "노션 대체 지식 관리 도구"
        icon: affine-light.svg

- Utility & Lifestyle:
    - Stirling-PDF:
        href: http://192.168.50.200:15002
        description: "PDF 관리"
        icon: stirling-pdf.svg
    - Mealie: 
        href: http://192.168.50.200:15003
        description: "레시피 관리"
        icon: mealie.svg
    - Rallly:
        href: https://rallly.junbeom.work
        description: "이벤트 계획 및 일정 관리"
        icon: rallly.svg
    - Shlink:
        href: http://192.168.50.200:15006
        description: "URL 단축 서비스"
        icon: shlink.svg
