services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    restart: unless-stopped
    ports:
      - 14005:8443
    volumes:
      - /opt/data/code-server/config:/config
      - /home/junbeom/obsidian-blog:/config/workspace/obsidian-blog
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Seoul
      - PASSWORD=${PASSWORD}
      - SUDO_PASSWORD=${SUDO_PASSWORD}
      - PROXY_DOMAIN=code-server.junbeom.work
      - DEFAULT_WORKSPACE=/config/workspace
      - PWA_APPNAME=code-server
networks: {}
