services:
  postgresql:
    image: postgres:16
    container_name: shared-postgres
    env_file:
      - .env
    environment:
      # 슈퍼유저(Root)의 비밀번호를 설정합니다.
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      TZ: Asia/Seoul
      LANG: ko_KR.utf8
    # DB 데이터 유실 방지를 위해 호스트 디렉토리에 저장합니다.
    volumes:
      - ./data:/var/lib/postgresql/data
      # 중요: 여러 DB를 생성하기 위한 초기화 스크립트 폴더 마운트
      - ./init-db:/docker-entrypoint-initdb.d
    # 다른 서비스들이 이 IP:5432로 접속할 수 있도록 포트를 외부에 노출합니다.
    ports:
      - 5432:5432
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  networks:
    default:
      name: shared-network
      external: true
networks: {}
