services:
  obsidian-blog:
    image: nginx:alpine
    container_name: obsidian-blog
    restart: unless-stopped
    ports:
      - 10007:80
    volumes:
      - /home/junbeom/quartz-blog:/usr/share/nginx/html:ro
      - /home/junbeom/quartz-blog/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - npm_default
networks:
  npm_default:
    external: true
