services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    ports:
      - 8080:8080
    volumes:
      - /opt/docker/stirling/stirling-data/tessdata:/usr/share/tessdata # OCR language files
      - /opt/docker/stirling/stirling-data/configs:/configs # Settings & database
      - /opt/docker/stirling/stirling-data/logs:/logs # Application logs
      - /opt/docker/stirling/stirling-data/pipeline:/pipeline # Automation configs
    environment:
      - SECURITY_ENABLELOGIN=false # Set true to enable user authentication
      - LANGS=en_GB # Interface language
    networks:
      - npm_default
    restart: unless-stopped
networks:
  npm_default:
    external: true
