services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actual
    ports:
      - 5006:5006
    volumes:
      - /opt/data/actual/:/data
    restart: unless-stopped
    healthcheck:
      # Enable health check for the instance
      test:
        - CMD-SHELL
        - node src/scripts/health-check.js
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
networks:
  default:
    name: actual-network
