services:
  cloudbeaver:
    container_name: cloudbeaver
    image: dbeaver/cloudbeaver:latest
    restart: unless-stopped
    volumes:
      - ./data:/opt/cloudbeaver/workspace
    ports:
      - 12000:8978
    networks:
      - postgresql_default
networks:
  postgresql_default:
    external: true
