services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    container_name: outline
    ports:
      - 14005:3000
    volumes:
      - /opt/data/outline/data:/var/lib/outline/data
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DEFAULT_LANGUAGE=ko_KR
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_URL=redis://outline-redis:6379
      - URL=https://outline.junbeom.work
      - UTILS_SECRET=${UTILS_SECRET}
      - PGSSLMODE=disable
      - SMTP_HOST=smtp.resend.com
      - SMTP_PORT=465
      - SMTP_USERNAME=resend
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_EMAIL=outline@junbeom.work
    networks:
      - default # Redis와의 통신용
      - postgresql-network
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: outline-redis
    expose:
      - "6379"
    volumes:
      - /opt/data/outline/redis.conf:/redis.conf
    command:
      - redis-server
      - /redis.conf
    networks:
      - default
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 30s
      retries: 3
networks:
  default:
    name: outline-network
  postgresql-network:
    external: true
