services:
  npmplus:
    container_name: npmplus
    image: docker.io/zoeyvid/npmplus:latest
    restart: unless-stopped
    ports:
      - 80:80/tcp # HTTP
      - 443:443/tcp # HTTPS
      - 443:443/udp # HTTP/3 (QUIC)
      - 10001:81/tcp # Admin UI
    networks:
      - npm_default
    environment:
      TZ: Asia/Seoul
      PUID: 1000
      PGID: 1000
      # --- CrowdSec ---
      LOGROTATE: true
      LOGROTATIONS: 7
      # --- Optimizer ---
      DISABLE_IPV6: true
    volumes:
      - ./data:/data
  crowdsec:
    container_name: npmplus_crowdsec
    image: docker.io/crowdsecurity/crowdsec:latest
    restart: unless-stopped
    ports:
      - 11003:8080
    networks:
      - npm_default
    environment:
      TZ: Asia/Seoul
      COLLECTIONS: crowdsecurity/nginx-proxy-manager
      GID: 1000
    volumes:
      - ./crowdsec/conf:/etc/crowdsec
      - ./crowdsec/data:/var/lib/crowdsec/data
      - ./data/logs:/var/log/npmplus:ro
    depends_on:
      - npmplus
networks:
  npm_default:
    name: npm_default
    external: true
    driver: bridge
