# ==================================================
# Docker Compose Sample
# Avg CPU: 
# Avg Memory: 
# ==================================================

services:
  {service_name}:
    image: {image_name}
    container_name: {service_name}
    restart: unless-stopped
    ports:
      - {host_port}:{container_port}
    volumes:
      - {host_path}:{container_path}
    environment:
      - {ENV_VAR_KEY}={ENV_VAR_VALUE}
    networks:
      - {network_name}
# ==================================================
# 헬스체크 - 서비스마다 healthcheck 방식이 다르므로 필요에 따라 수정 필요
# ==================================================
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:{healthcheck_port}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
# ==================================================
# 리소스 제한 - Avg * 1.5 ~ 2 정도로 설정 권장, 필요시 조정
# ==================================================
    deploy:
      resources:
        limits:
          cpus: "{cpu_limit}"
          memory: "{memory_limit}"
# ==================================================
# 로그 설정
# ==================================================
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service={service_name}"

# ==================================================
# 네트워크 설정
# ==================================================
networks:
  {network_name} : {}