services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    restart: unless-stopped
    ports:
      - 13001:8080
    volumes:
      - ./data/tessdata:/usr/share/tesseract-ocr/5/tessdata:rw
      - ./data/configs:/configs:rw
      - ./data/logs:/logs:rw
      - ./data/pipeline:/pipeline:rw
    environment:
      # Security & Authentication
      - SECURITY_ENABLELOGIN=false
      # Localization
      - SYSTEM_DEFAULTLOCALE=ko_KR
      - OCR_LANGS=kor,eng,chi_tra
      # Features
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      # System Configuration
      - STIRLING_PDF_PROCESS_TIMEOUT_MINUTES=120
      - DOCKER_ENABLE_SECURITY=false
      - SYSTEM_ROOTURIPATH=/
      - SYSTEM_CUSTOMSTATICFILEPATH=/customFiles/
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: "6"
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - npm_default
networks:
  npm_default:
    external: true
