services:
  kopia:
    image: kopia/kopia:latest
    hostname: ${HOSTNAME:-KopiaServer}
    container_name: kopia
    restart: unless-stopped
    ports:
      - 14000:51515
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --address=0.0.0.0:51515
      - --server-username=${KOPIA_ADMIN}
      - --server-password=${KOPIA_ADMIN_PASSWORD}
    environment:
      KOPIA_PASSWORD: ${KOPIA_REPOSITORY_PASSWORD}
      USER: junbeom-cho
      TZ: Asia/Seoul
      RCLONE_CONFIG: /app/config/rclone.conf
    volumes:
      # --- Default Volumes ---
      - ./app/config:/app/config
      - ./app/cache:/app/cache
      - ./app/logs:/app/logs
      # --- 백업 대상 ---
      - /opt:/data/opt:ro
      # --- 스냅샷 마운트용 (복구 시 사용) ---
      - /tmp:/tmp:shared
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
networks: {}
