services:
  it-tools:
    container_name: it-tools
    image: ghcr.io/sharevb/it-tools:nightly
    pull_policy: always
    restart: unless-stopped
    ports:
      - 8081:8080
    networks:
      - npm_default
networks:
  npm_default:
    external: true
