services:
  app:
    image: lepresidente/nginxproxymanager:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 81:81
    environment:
      TZ: Asia/Seoul
      DB_MYSQL_HOST: db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: npm
      DB_MYSQL_PASSWORD: ${NPM_DB_PASSWORD}
      DB_MYSQL_NAME: npm
      CROWDSEC_OPENRESTY_BOUNCER: |
        ENABLED=true
        API_URL=http://crowdsec:8080
        API_KEY=${CROWDSEC_BOUNCER_APIKEY}
        CACHE_EXPIRATION=1s
    volumes:
      # NPM 데이터 경로
      - /opt/docker/npm/data:/data
      - /opt/docker/npm/letsencrypt:/etc/letsencrypt
    networks:
      - npm_default
      - crowdsec_default
    depends_on:
      - db
      - crowdsec

  db:
    image: jc21/mariadb-aria:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${NPM_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: npm
      MYSQL_USER: npm
      MYSQL_PASSWORD: ${NPM_DB_PASSWORD}
      MARIADB_AUTO_UPGRADE: "1"
    volumes:
      # DB 데이터 경로
      - /opt/docker/npm/mysql:/var/lib/mysql
    networks:
      - npm_default

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: unless-stopped
    environment:
      COLLECTIONS: "crowdsecurity/nginx-proxy-manager crowdsecurity/base-os"
      GID: "${GID-1000}"
    volumes:
      # [수정됨] 이름(crowdsec-db) 대신 실제 경로 사용
      - /opt/docker/crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - /opt/docker/crowdsec/config:/etc/crowdsec
      - /opt/docker/crowdsec/data:/var/lib/crowdsec/data
      # 로그 경로 (read-only 에러 방지용)
      - /opt/docker/npm/data/logs:/npm_logs:ro
    networks:
      - crowdsec_default

networks:
  npm_default:
    external: true
  crowdsec_default:
    driver: bridge