version: "3.8"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # 외부 접속용 (공유기 포트포워딩 대상)
      - '80:80'
      - '443:443'
      # 관리자 페이지 (Tailscale로만 접근)
      - '81:81'
    volumes:
      # 아까 만든 폴더와 연결
      - /opt/docker/npm/data:/data
      - /opt/docker/npm/letsencrypt:/etc/letsencrypt
    healthcheck:
      # 프로그램이 잘 살아있는지 10초마다 확인
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s